spring:
  application:
    name: evision
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    include:
      - private

file:
  upload:
    path: ./uploads/

server:
  port: 8081

mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.kh.evision.**.vo, com.kh.evision.**.dto, com.kh.evision.file
  mapper-locations: classpath:mapper/**/*.xml
  

logging:
  level:
    root: INFO
    com.kh.evision: INFO
